# permissions for end users to edit ferretdbs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ferretdb-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ferretdb-operator
    app.kubernetes.io/part-of: ferretdb-operator
    app.kubernetes.io/managed-by: kustomize
  name: ferretdb-editor-role
rules:
- apiGroups:
  - ferretdb.ferretdb.com
  resources:
  - ferretdbs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ferretdb.ferretdb.com
  resources:
  - ferretdbs/status
  verbs:
  - get
